[phases.setup]
nixPkgs = ["nodejs-22_x", "pnpm-9_x"]

[phases.install]
cmds = [
    "cd backend",
    "npm install -g corepack@0.24.1",
    "corepack enable",
    "corepack prepare pnpm@latest --activate",
    "pnpm config set frozen-lockfile false",
    "pnpm install"
]

[phases.build]
cmds = [
    "cd backend",
    "pnpm run build"
]

[start]
cmd = "cd backend && ./start.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"