#!/bin/bash

echo "🎯 Creating KCT VIP Demo Customer"
echo "=================================="
echo ""

BASE_URL="https://backend-production-7441.up.railway.app"

echo "Creating fully populated demo customer..."
echo ""

RESPONSE=$(curl -s -X POST "$BASE_URL/admin/demo-customer" \
  -H "Content-Type: application/json")

if echo "$RESPONSE" | jq -e '.success' >/dev/null 2>&1; then
    echo "✅ SUCCESS! Demo customer created"
    echo ""
    CUSTOMER_ID=$(echo "$RESPONSE" | jq -r '.customer.id')
    echo "📧 Email: john.smith.vip@kctmenswear.com"
    echo "🆔 Customer ID: $CUSTOMER_ID"
    echo ""
    echo "=================================="
    echo "📊 CUSTOMER PROFILE INCLUDES:"
    echo "=================================="
    echo ""
    echo "💰 ANALYTICS:"
    echo "  • Lifetime Value: $15,750"
    echo "  • Average Order: $525"
    echo "  • Total Orders: 30"
    echo "  • Risk Score: Low"
    echo ""
    echo "🏆 LOYALTY:"
    echo "  • Tier: Platinum"
    echo "  • Points: 15,750"
    echo "  • Benefits: 20% discount, Free alterations"
    echo ""
    echo "💒 WEDDING EVENT:"
    echo "  • Date: June 15, 2025"
    echo "  • Role: Groom"
    echo "  • Party Size: 8 groomsmen"
    echo "  • Rental Value: $4,200"
    echo ""
    echo "👔 MEASUREMENTS:"
    echo "  • Suit: 42R"
    echo "  • Shirt: 16.5/34"
    echo "  • Shoe: 10.5"
    echo ""
    echo "📝 INTERNAL NOTES:"
    echo "  • VIP - Premium service required"
    echo "  • Wedding party rental in progress"
    echo "  • Prefers morning appointments"
    echo "  • Allergic to wool"
    echo ""
    echo "🏷️ SEGMENTS:"
    echo "  • VIP Customer"
    echo "  • Frequent Buyer"
    echo "  • Wedding Party"
    echo "  • Platinum Tier"
    echo ""
    echo "=================================="
    echo "🔍 HOW TO VIEW:"
    echo "=================================="
    echo ""
    echo "1. In Admin Panel:"
    echo "   Go to Customers → Search for 'john.smith.vip@kctmenswear.com'"
    echo "   (Shows basic info)"
    echo ""
    echo "2. Via Enhanced API:"
    echo "   GET $BASE_URL/admin/customers-enhanced/$CUSTOMER_ID?include_analytics=true"
    echo "   (Returns ALL enhanced data)"
    echo ""
    echo "3. Test the API:"
    echo "   curl '$BASE_URL/admin/customers-enhanced/$CUSTOMER_ID?include_analytics=true'"
    echo ""
else
    echo "ℹ️ Note: Demo customer may already exist or requires authentication"
    echo "$RESPONSE" | jq '.' 2>/dev/null || echo "$RESPONSE"
fi