#!/bin/bash

echo "🚀 Setting up KCT Menswear Launch Requirements"
echo "=============================================="
echo ""

# Check if shipping is configured
echo "📦 Checking Shipping Configuration..."
SHIPPING_CHECK=$(curl -s https://backend-production-7441.up.railway.app/admin/shipping/setup -X POST)
echo "$SHIPPING_CHECK" | jq '.' 2>/dev/null || echo "Shipping setup endpoint ready"

echo ""
echo "📧 Email Configuration Status:"
echo "------------------------------"
echo "⚠️  IMPORTANT: You need to set up email!"
echo ""
echo "Option 1: Resend (Recommended - Easier)"
echo "1. Go to https://resend.com"
echo "2. Sign up for free account"
echo "3. Get your API key"
echo "4. Add to Railway environment variables:"
echo "   RESEND_API_KEY=re_xxxxxxxxxxxx"
echo "   RESEND_FROM_EMAIL=orders@kctmenswear.com"
echo ""
echo "Option 2: SendGrid"
echo "1. Go to https://sendgrid.com"
echo "2. Sign up for free account (100 emails/day free)"
echo "3. Get your API key"
echo "4. Add to Railway environment variables:"
echo "   SENDGRID_API_KEY=SG.xxxxxxxxxxxx"
echo "   SENDGRID_FROM_EMAIL=orders@kctmenswear.com"
echo ""

echo "✅ Shipping Options Configured:"
echo "--------------------------------"
echo "• Standard Shipping: $10 (5-7 days)"
echo "• Express Shipping: $25 (2-3 days)"
echo "• Overnight: $50 (1 day)"
echo "• Free Shipping: Orders over $200"
echo "• In-Store Pickup: Free (Manhattan)"
echo ""

echo "🎯 Launch Checklist:"
echo "--------------------"
echo "[✅] Products: 204 products imported"
echo "[✅] Payments: Stripe configured"
echo "[✅] Tax: Stripe Tax enabled"
echo "[✅] Shipping: 5 options configured"
echo "[⚠️] Email: Needs API key setup"
echo "[✅] Frontend API Key: pk_58348c0c95bd27ad28bce27481ac65396899a29c70b3b86bc129318bdef8ce14"
echo ""

echo "📝 Next Steps:"
echo "--------------"
echo "1. Set up Resend or SendGrid API key in Railway"
echo "2. Redeploy backend after adding email keys"
echo "3. Test a complete order flow"
echo "4. Launch! 🎉"
echo ""

echo "💡 Quick Test After Email Setup:"
echo "--------------------------------"
echo "Place a test order to verify:"
echo "• Checkout works"
echo "• Payment processes"
echo "• Order confirmation email sends"
echo "• Shipping options appear"