[providers]
node = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm install && npm run build"]

[start]
cmd = "npm start"